version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_API_URL=/api  # Use API proxy through Nginx
    image: usmanqasim7/myapp3-client:latest
    ports:
      - "4000:80"  # Maps host port 80 to container port 80
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: usmanqasim7/myapp3-server:latest
    ports:
      - "6000:5000"  # Maps host port 5000 to container port 5000
    environment:
      - MONGO_URI=mongodb+srv://usmanqasimcsa:usmanawt@cluster0.jnelddy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - NODE_ENV=production
      - CLIENT_URL=http://client  # Correct URL for CORS
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
