version: "3.8"

services:
  frontend:
    build: .
    image: ru0300usman/myapp3:latest
    ports:
      - "4000:5000"  # Maps port 4000 on host to port 5000 in container (server port)
    environment:
      - MONGO_URI=mongodb+srv://usmanqasimcsa:usmanawt@cluster0.jnelddy.mongodb.net/
      - NODE_ENV=production
    # No local dependencies since we're using MongoDB Atlas

# No volumes needed since we're using MongoDB Atlas cloud database