version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: ru0300usman/myapp3-client:latest
    ports:
      - "80:80"  # Maps host port 80 to container port 80
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: ru0300usman/myapp3-server:latest
    ports:
      - "5000:5000"  # Maps host port 5000 to container port 5000
    environment:
      - MONGO_URI=mongodb+srv://usmanqasimcsa:usmanawt@cluster0.jnelddy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - NODE_ENV=production
      - CLIENT_URL=http://server
