version: "3.8"

services:
  frontend:
    build: .
    image: ru0300usman/myapp3:latest
    ports:
      - "3000:80"
    environment:
      - MONGO_URI=mongodb+srv://usmanqasimcsa:usmanawt@cluster0.jnelddy.mongodb.net/
      - NODE_ENV=production
    # No local dependencies since we're using MongoDB Atlas

# No volumes needed since we're using MongoDB Atlas cloud database